### ISSUE TITLE
CRC bidsmap template

### ISSUE THREAD

**Issue by Remi-Gau** [nbeliy/bidsme#7]
I guess it would also make sense to have place where to put some bidsmap template for the CRC. For example for some of the "typical sequences" on the Terra or the Prisma of the CRC.

**Comment by nbeliy** [comment]
It is already. The default template is generated on the basis of MSfatigue study (the only study where the bidsification shema was officiallised). I was planning together with Evelyne to incorporate all CRC protocols, but these plans was postponed due to apocalipsis.

I will expand existing template, following new bidsifications in CRC. After all template is a just bidsmap with placeholders.

**Comment by Remi-Gau** [comment]
OK cool I will try to help you with this then as since we are using some "default" sequences from the Terra it would make sense to add them to the template.

Do you try to have a template to support all the different type of inputs (DICOM, nitfit + json, ...) ?
